server:
  servlet:
    context-path: /aye-mob-service
  port: 8083
  #  ssl:
  #    enabled: true
  #    key-store-type: JKS
  #    key-store: classpath:web-keystore.jks
  #    key-password: changeit
  #    key-alias: web-service
  #    trust-store: classpath:web-truststore.jks
  #    trust-store-password: changeit
  #    trust-store-type: JKS
  #    client-auth: need

backend:
  service:
    url: http://localhost:8443/aye-backend-service